[zapret]
exe_path = "zapret/bin/winws.exe"
presets_dir = "zapret"
last_preset = "general"
args = []
autostart = false

[ui]
theme = "dark"
remember_tab = true
bar_style = "rainbow"

[updater]
repo = "Flowseal/zapret-discord-youtube"
check_on_start = true

[dns]
servers = [
    "111.88.98.50",
    "111.88.96.51",
]
